# Generated by Django 5.1.4 on 2024-12-11 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 11, 3, 56, 25, 784922, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
